package com.github.coolcool.sloth.lianjiadb.controller.restfulapi;

import java.util.*;

import com.alibaba.fastjson.JSONObject;
import com.github.coolcool.sloth.lianjiadb.model.House;
import com.github.coolcool.sloth.lianjiadb.service.impl.support.LianjiaWebUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.github.coolcool.sloth.lianjiadb.service.HouseService;
import com.github.coolcool.sloth.lianjiadb.common.Page;
import javax.annotation.Generated;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
@RestController
@EnableSwagger2
@RequestMapping(value = "/house")
public class HouseController {

	@Autowired
	private HouseService houseService;

	@RequestMapping(value = "/test", method = RequestMethod.GET)
	public String test() {
		return "success";
	}

	@RequestMapping(value = "/save", method = RequestMethod.POST)
	public void save(@ModelAttribute House house) {
		houseService.save(house);
	}

	@RequestMapping(value = "/delete/{id}", method = RequestMethod.POST)
	public void  delete(@PathVariable Object id) {
		houseService.deleteById(id);
	}

	@RequestMapping(value = "/view/{id}", method = RequestMethod.GET)
	public House  view(@PathVariable Object id) {
		return houseService.getById(id);
	}

	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public void update(@ModelAttribute House house) {
		houseService.update(house);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	public Integer  count() {
		return houseService.count();
	}

	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public List<House> list() {
		return houseService.list();
	}

	@RequestMapping(value = "/page", method = RequestMethod.GET)
	public Page<House> page(@RequestParam int pageNo, @RequestParam int pageSize) {
		return houseService.page(pageNo, pageSize);
	}

}