package com.github.coolcool.sloth.lianjiadb.service;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.Process;
import com.github.coolcool.sloth.lianjiadb.common.Page;
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface ProcessService{


	void fetchHouseUrls();

	void fetchHouseDetail();

	Integer save(Process process);

	Integer count();

	Process getById(Object id);

	void deleteById(Object id);

	void update(Process process);

	List<Process> list();

	Page<Process> page(int pageNo, int pageSize);

	Integer increment();
}