package com.github.coolcool.sloth.lianjiadb.model;

import javax.annotation.Generated;

@Generated(
	value = {
	"https://github.com/coolcooldee/sloth",
	"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public class HttpProxy {

	private Integer id;
	private String host;
	private Integer port;
	private String location;
	private Integer status;
	private String anonymous;
	private java.util.Date createtime;

	public HttpProxy(){

	}

	public HttpProxy(String host, Integer port, String location) {
		this.host = host;
		this.port = port;
		this.location = location;
	}

	public HttpProxy(String host, Integer port, String location, String anonymous) {
		this.host = host;
		this.port = port;
		this.anonymous = anonymous;
		this.location = location;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	} 
	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getAnonymous() {
		return anonymous;
	}

	public void setAnonymous(String anonymous) {
		this.anonymous = anonymous;
	}

	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	} 
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public java.util.Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(java.util.Date createtime) {
		this.createtime = createtime;
	} 
}
